baseURL = "http://localhost:1313/"
languageCode = "tr"
title = "Site Başlığı"
# theme = ""  # tema yoksa boş bırakabilirsin
disableKinds = ["RSS"]


	
# Site genel açıklaması (SEO için)
[params]
  description = "Site açıklaması buraya yazılacak."


[taxonomies]
  category = "categories"
  tag = "tags"

[permalinks]
  categories = "/:slug/"   # Kategori URL’lerini /oyun gibi yapar
  post = "/:slug/"
  
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.parser]
      wrapInParagraph = false


[outputs]
  page = ["HTML"]
  section = ["HTML"]
  home = ["HTML", "search"]


[outputFormats.search]
  mediaType = "application/json"
  baseName = "search"
  isPlainText = true
  notAlternative = true



